variables:
  MAVEN_OPTS: "-Dhttps.protocols=TLSv1.2 -Dmaven.repo.local=$CI_PROJECT_DIR/.m2/repository -Dorg.slf4j.simpleLogger.log.org.apache.maven.cli.transfer.Slf4jMavenTransferListener=WARN -Dorg.slf4j.simpleLogger.showDateTime=true -Djava.awt.headless=true"
  MAVEN_CLI_OPTS: "--batch-mode --errors --fail-at-end --show-version -DinstallAtEnd=true -DdeployAtEnd=true"


image: "maven:latest"

development-job:
  except:
    - 'tags'
  script:
    - 'mvn versions:set -DnewVersion=1.0.0-SNAPSHOT'
    - 'mvn versions:update-child-modules'
    - 'mvn -DgitVer=git-$CI_COMMIT_SHORT_SHA- clean install -s ci_settings.xml'
  artifacts:
    paths:
      - '*/target/*.jar'

release-job:
  only:
    - 'tags'
  script:
    - 'mvn versions:set -DnewVersion=1.0.0'
    - 'mvn versions:update-child-modules'
    - 'mvn -DgitVer='''' clean deploy -s ci_settings.xml javadoc:javadoc'
  artifacts:
    paths:
      - '*/target/*.jar'
      - '*/target/site/*'
